cloudinary:
  service: Cloudinary
  cloud_name: "dxumpomm9"
  api_key: "471847129825499"
  api_secret: "n5KAv_JeFi1zcC3JmIKjQ-UI4rQ"
  url: "cloudinary://471847129825499:n5KAv_JeFi1zcC3JmIKjQ-UI4rQ@dxumpomm9"
